import groovy.xml.XmlSlurper
import java.io.File

def expectedJacocoFile = "target/jacoco.xml"
File reportFile = new File(basedir, expectedJacocoFile)

assert reportFile.isFile() : "$reportFile does not exist"
assert reportFile.length() > 0 : "$reportFile is empty"

def report = new XmlSlurper().parse(reportFile)

def emptyClasses = report.package.class.findAll { it.counter.size() == 0 }
assert emptyClasses.size() == 0 : "there should be no classes without a counter, but found " + emptyClasses*.@name

def coveredClass = report.package.class.findAll { it.@name == 'io/github/miracelwhipp/neincoco/it/generated/Covered' }
assert coveredClass.size() == 1 : "covered class not found"

def nestedClass = report.package.class.findAll { it.@name == 'io/github/miracelwhipp/neincoco/it/generated/ThisIsAssumedToBeAnAutoGeneratedClass$Nested' }

assert nestedClass.size() == 0 : "the nested class should be ignored"

def sourceFile = report.package.sourcefile.findAll { it.@name == 'ThisIsAssumedToBeAnAutoGeneratedClass.java' }

assert sourceFile.size() == 0 : "The source file for the auto generated class should be ignored"

def expectedSourceDirFile = "target/jacoco-source-directories.txt"
def sourceDirectories = new File(basedir, expectedSourceDirFile)

assert sourceDirectories.isFile() : "$expectedSourceDirFile does not exist"
assert sourceDirectories.length() > 0 : "$expectedSourceDirFile is empty"

assert sourceDirectories.text == """src${File.separator}main${File.separator}java
target${File.separator}generated-sources${File.separator}annotations
"""

return true