name: build commits

on:
  push:
    branches-ignore: [ main ]
  pull_request: {}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: execute maven
        run: mvn --batch-mode install -e
