name: deploy default branch

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          gpg-private-key: ${{ secrets.PGP_KEY }}
          gpg-passphrase: ${{ secrets.SIGNATURE_PASSWORD }}
      - name: execute maven
        run: export GPG_TTY=$(tty) && mvn --batch-mode deploy -e
        env:
          GPG_KEY_NAME: miracelwhipp
          GPG_PASS_PHRASE: ${{ secrets.SIGNATURE_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
